## <!-- File automatically generated using DocOnce (https://github.com/doconce/doconce/):
doconce format ipynb tmp_mako__34.oppgaver.do.txt --userdef_environment_file=/Users/alexajo/github/bios1100-uke-for-uke/general/userdef_environments.py --skip_inline_comments --encoding=utf-8 --language=Norwegian --ipynb_non_editable_text --execute=abort --output=/Users/alexajo/github/bios1100-uke-for-uke/pub/34/34.oppgaver-løsning.ipynb --execute -->

# BIOS1100 H22 oppgaver uke 34 - løsningsforslag

## Oppgave 1: Rekkefølge av celler

* Lag tre kodeceller med disse komandoer:

In [2]:
mitt_navn = "Alexander Rybak"

In [3]:
mitt_navn = "Bobbysocks"

In [4]:
print(mitt_navn)

Bobbysocks


* kjør cellene i forskjellige rekkefølger, f. eks.

  * `1. - 2. - 3.`

  * `2. - 3. - 1.`

  * `3. - 3. - 3.`

* Diskuter i par hva som skjer og om du forstår hvorfor

<!-- --- begin answer of exercise --- -->
**Fasit.**
Det er viktig å merke seg dette:
* kodecellene i Notebook kan kjøres i hvilken som helst rekkefølge

* tallene til venstre for kodecellene, de i firkantede klammer, kan hjelpe deg å finne ut hvilken rekkefølge

* verdiene variabler representerer er altid et resultat av den siste gangen den ble satt

Et viktig råd er dermed å altid kjøre kodecellene (igjen) i den rekkefølgen
de er i notebooken.

<!-- --- end answer of exercise --- -->

## Oppgave 2: Regnerekkefølgen

Evaluer for hånd hva følgende Python kommando vil gi som resultat.

In [5]:
print(float("1" + "0")**2/2 +1)

51.0


Kjør deretter denne kodelinjen for å sjekke om du fikk det korrekte svaret.

<!-- --- begin answer of exercise --- -->
**Fasit.**
51.0

<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
* `"1" +  "0"` blir `"10"` (en tekststreng)

* `float("10")` blir `10.0` (et flyttal (float))

* `10**2/2 + 1` blir `51.0` (et flyttal (float)) fordi de regnes ut som `((10**2)/2) + 1`

<!-- --- end solution of exercise --- -->

<!-- Engelsk versjon: fix_error.do.txt -->

## Oppgave 3: Finn feilen(e)

Python programmene nedenfor inneholder en eller flere feil.
Først skal du identifisere disse feilene *uten å kjøre programmet*,
og deretter korrigere dem slik at programmene kjører uten feil.

**a)**
Programmet med feilen(e):

```Python
        vekt_kg = 55
        vekt_pund = 2.2 * vekt_kg
        print(vekt_kg, "kilogram er det samme som", vekt pund 'Britiske pund')
```

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
* `vekt pund` skal være `vekt_pund`

* det mangler en komma foran `'Britiske pund'`

In [6]:
vekt_kg = 55
vekt_pund = 2.2 * vekt_kg
print(vekt_kg, "kilograms er det samme som", vekt_pund, 'Britiske pund')

55 kilograms er det samme som 121.00000000000001 Britiske pund


<!-- --- end solution of exercise --- -->

**b)**
Programmet med feilen(e):

```Python
        lengde_m = 66
        lengde_ft = 3.28 * lengde_m
        print lengde_m, 'meter er det samme som", lengde_ft, fot")
```

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
* det mangler en `(` etter `print`

* blanding av enkle og doble anførselestegn

* manglende anførselestegn foran `fot`

In [7]:
lengde_m = 66
lengde_ft = 3.28 * lengde_m
print(lengde_m, "meter er det samme som", lengde_ft, "fot")

66 meter er det samme som 216.48 fot


<!-- --- end solution of exercise --- -->

**c)**
Programmet med feilen(e):

```Python
        sekunder = 10**8
        minuter = sekunder / 60
        timer = minuter / 60
        dager = timer / 60
        aar = dager / 365.25
        print(sekund, "sekunder er det samme som",, round(aar), 'aar')
```

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
* to kommaer etter `er det samme som"`

* `sekund` should be `sekunders`

* det er 24 timer i et døgn, ikke 60

In [8]:
sekunder = 10**8
minuter = sekunder / 60
timer = minuter / 60
dager = timer / 24
aar = dager / 365.25
print(sekunder, "sekunder er det samme som", round(aar), 'aar')

100000000 sekunder er det samme som 3 aar


<!-- --- end solution of exercise --- -->

**d)**
Hvilen av feilene er *ikke* av type `SyntaxError` (syntaks feil)?
Hva slags feil ville du kalle det? Og hvordan oppdager man slike feil?

<!-- --- begin answer of exercise --- -->
**Fasit.**
Feilen i beregning av antall timer i et døgn er ikke en syntaks feil,
men en 'tenkefeil'. Programmet kjører fint, men resultatet til slutt er feil.
Slike feil er ofte vanskeligere å oppdage siden Python ikke sier i fra om dem.
<!-- --- end answer of exercise --- -->

## Oppgave 4: Refleksjon , og +

Bruk 5 minutter, i par, til å skrive ned alle forskjeller
mellom det å bruke `,` og `+` til å sette sammen strenger i `print` kommandoer

<!-- --- begin answer of exercise --- -->
**Fasit.**
* `,` legger til et mellomrom

* `,` kan brukes for å kombinere strenger og tall

* `+` legger ikke til et mellomrom

* `+` forventer bare strenger, og krever konverting til strenger for tall (med hjelp av `str()`)

<!-- --- end answer of exercise --- -->

## Oppgave 5: talltyper

Diskuter med din nabo: for hver av disse kodelinjene, hva skrives ut når de kjøres:

In [9]:
print(str(1) + str(int(2.0)))

print(int(str(int(str("45")))))

print(float("1.23"))

print(float(1.23))

print(float("1"))

print(float(1))

print(int("1.23"))

12
45
1.23
1.23
1.0
1.0


ValueError: invalid literal for int() with base 10: '1.23'

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
Litt forklaring til den siste oppgaven:

        ValueError: invalid literal for int() with base 10: '1.23'


Nokså kryptisk, men du skjønner kanskje feilen:
strengen som konverteres fører ikke til et heltall.

<!-- --- end solution of exercise --- -->

## Oppgave 6: float versus float()

I ukens samkoding ble både `float` and `float()` vist.
Men hva er egentlig forskjellen mellom `float` med og uten parentes bak?

Bruk gjerne noen Python kommandoer eller program for å illustret svaret ditt.

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
`float`, uten parentes, er en type variabel:

In [10]:
a = 1.2
print(type(a))

<class 'float'>


`float()`, med parentes, er en funksjon som konverterer en verdi av en annen
type til `float`:

In [11]:
b = "1.2"
print(float(b))

1.2


<!-- --- end solution of exercise --- -->

## Flere Python oppgaver

<div class="alert alert-block alert-info">
Du finner flere oppgaver for å øve denne ukens nye Python-konsepter
blant "Ekstraøvelser" for denne ukens kapittel.
Se Canvas (under 'Pensum').
</div>

<!-- size differences bacterial and human cells -->

<!-- English: 01_scientific_calculator/cell_volume01.do.txt -->

## Oppgave 7: Volum av en celle

Man hører ofte at kroppene våre "består" av flere bakterieceller, enn våre egne celler.
Men størrelsen på disse cellene er ganske forskjellige.
Celler varierer veldig i størrelse, fra nevroner som strekker seg flere meter,
til våre relativt små røde blodlegemer på mindre enn 10 $\mu$m.

Radiusen på en menneskelig kinncelle er omtrent 50 $\mu$m,
mens en bakteriecelle ikke er større enn 5 $\mu$m.
Et vanlig estimat er en 100 ganger forskjell i radius,
det vil si at radiusen til en bakteriecelle er 0,5 mikrometer ($\mu$m),
og vi vil bruke den til denne øvelsen.

Svarene på spørsmålene nedenfor skal være en full setning.

**a)**
Skriv et Python-program som beregner volumet til en gjennomsnittlig menneskelig kinncelle,
og skriver den ut.
Volumet til en kule er gitt av formelen $\frac{4}{3}*\pi* radius^3$.

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [12]:
from pylab import *
radius_kinncelle = 50
vol_kinncelle = (4/3) * pi * radius_kinncelle ** 3
print ("Volumet til en kinncelle er" + str(vol_kinncelle) + "mikrometer")

Volumet til en kinncelle er523598.7755982988mikrometer


<!-- --- end solution of exercise --- -->

**b)**
Bruk programmet til å beregne størrelsen på den gjennomsnittlige bakteriecellen.

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [13]:
radius_bakt = 0.5
vol_bakt = (4/3) * pi * radius_bakt ** 3
print ("Volumet til en bakteriecelle er" + str(vol_bakt) + "mikrometer")

Volumet til en bakteriecelle er0.5235987755982988mikrometer


<!-- --- end solution of exercise --- -->

**c)**
Skriv et program som beregner mengden bakterieceller som vil være nødvendig
for å fylle volumet tatt opp av en gjennomsnittlig menneskelig kinncelle.

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [14]:
vol_ratio = vol_kinncelle / vol_bakt
print("Mengden E. coli-celler som kan passe inn i en menneskelig celle er" + str (vol_ratio))

Mengden E. coli-celler som kan passe inn i en menneskelig celle er1000000.0


Hvis du avrundet tallene før du skrev ut, ville svaret være litt annerledes:

In [15]:
vol_kinncelle = round((4/3) * pi * radius_kinncelle ** 3, 2)
vol_bakt = round((4/3) * pi * radius_bakt ** 3, 2)
vol_ratio = round(vol_kinncelle / vol_bakt, 2)
print(vol_ratio)

1006920.73


<!-- --- end solution of exercise --- -->

**d)**
Kan du forklare forholdet gitt den 100-ganger forskjellen i radius?

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
Svaret, $1000000$, er kuben til forskjellen i radius, $100^3$,
forklart ved at for å beregne volumet må man ta kuben av radiusen.
<!-- --- end solution of exercise --- -->

<!-- camel heat and body temperature -->

## Oppgave 8: Camel body temperature

### Part 1: heating water

**a)**
1 calorie is the amount of energy needed to increase the temperature of 1g of water by 1 degree celsius. 1 calorie equals 4.184 joules.

Write a Python program that converts 7160 joules to calories, rounds the result to 0 decimals and *then* prints the result as a full sentence:

        7160 joules equals _____ calories.


Note that rounding must be done *before* printing the results.

<!-- --- begin answer of exercise --- -->
**Fasit.**
7160 joules equals 1711 calories.
<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [16]:
joules = 7160
calories = round(joules/4.184)
# Prints the amount of calories given by the input of joules
print(str(joules), "joules equals", str(calories), "calories.")

7160 joules equals 1711 calories.


Also correct is when `+` is used, but then there *have* to be the correct number of spaces around the text:

In [17]:
print(str(joules) + " joules equals " + str(calories) + " calories.")

7160 joules equals 1711 calories.


<!-- --- end solution of exercise --- -->

**b)**
Now write a program that converts the number of calories from your first program back to joules, rounds the result to 0 decimals, and *then* prints the result as a full sentence. Do you get the same amount of joules back?

<!-- --- begin answer of exercise --- -->
**Fasit.**
1711 calories equals 7159 joules; we lose one calorie due to the rounding.
<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [18]:
# Reverse calculator
# it is good practice (but not essential) to use a new name for the 'joules' variable
joules2 = round(calories * 4.184)
print(str(calories) + " calories equals " + str(joules2) + " joules")

1711 calories equals 7159 joules


<!-- --- end solution of exercise --- -->

**c)**
The calorie is a very small unit, and although we in everyday speech indeed use the term "calories" when referring to the energy contents of food, the numbers we use and the numbers found on the back of food packaging, is that of kilocalories or kcal (1000 calories). The relationship between a kcal, and a kjoule is the same as for calories and joules: $1 \text{kcal} = 4.184 \text{kjoules}$. The relationship between kcal and water heating is also preserved, but upscaled; 1kcal heats 1000g of water by 1 degree celsius.

Write a Python program that calculates how many joules are required to heat a bucket with 10L of water from 21 degrees celsius to boiling (100 degrees celsius). Assume that the heat transfer is instantaneous, and that no heat is lost in the process. Do *not* use any rounding in this program.

At the end, your program should print a full sentence like this:

        ____ kjoules are needed to heat 10L of water from 21 degrees C to boiling.


<!-- --- begin answer of exercise --- -->
**Fasit.**
3305.36 kjoules are needed to heat 10L of water from 21 degrees C to boiling.
<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [19]:
# Start by finding the amount of degrees of heating required
starting_temp = 21
desired_temp = 100
temp_diff = desired_temp - starting_temp

# Define the amount of water and amount of joules in a kcal
water_amount = 10
joules_per_calorie = 4.184

# Calculate kilojoules needed
kjoules_needed = joules_per_calorie * water_amount * temp_diff

print(str(kjoules_needed) + " kjoules are needed to heat 10L of water from 21 degrees C to boiling.")

3305.36 kjoules are needed to heat 10L of water from 21 degrees C to boiling.


<!-- --- end solution of exercise --- -->

**d)**
What type of variable is your answer to the last exercise? Show how you found out.

<!-- --- begin answer of exercise --- -->
**Fasit.**
The answer is of type `float` (because the 'joules per calorie' conversion results in a `float`).
<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [20]:
print(type(kjoules_needed))

<class 'float'>


<!-- --- end solution of exercise --- -->

### Part 2: Camels

<!-- Copyright John O'Neill -->
<!-- Licensed under Wikimedia Commons free media -->
<!-- dom:FIGURE:[figures/camel.jpg, alt="A camel in the desert", width=400, frac=0.4] -->
<!-- begin figure -->

<img src="figures/camel.jpg" alt="A camel in the desert" width="400"><p style="font-size: 0.9em"><i>Figur 1</i></p>
<!-- end figure -->

Contrary to popular belief, animals of the genus *camelus*, such as camels and dromedarys, do not carry volumes of water in the "humps" on their backs. Although it is indeed true that they can drink and store large amounts of water, and survive for a long time without drinking, camels deal with the heat in much more interesting ways than one might expect. Two important adaptations in camels in order to deal with heat are a large body with concentrated fatty deposits in the "humps", and a high tolerance for changes in body temperature. The fat acts as a buffer that soaks thermal energy, causing the temperature rise in the body as a whole to be quite slow; there is simply a lot of body to heat up! During cold desert nights, the effect is reversed and the body is cooled more slowly than in a smaller and leaner body. Allowing themselves to be heated also reduces the thermal gradient against the environment, and thus the heating slows as the camel's body temperature rises.

**e)**
Assume that a camel with a mass of 470kg receives a net heat gain averaging 90 $\frac{joules}{second}$ throughout a day lasting 13.5 hours. Our camel consists of 55% water, and we will assume that the water is the only thing that affects body temperature. The camel starts out in the morning at a body temperature of 35.5 degrees celsius. Write a python program that calculates the final body temperature at the end of the day, rounded to two decimals.

<!-- --- begin answer of exercise --- -->
**Fasit.**
The final body temperature of the camel is 39.54 degrees celsius.
<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**
We'll save intermediate results in variables so we can reuse them or
print their content.

We know that 1kcal heats 1000g of water by 1 degree celsius.

We thus need to determine
* the amount of kcal gained during the day

* the amount of water that is being warmed

We will first determine the total amount of energy the camel receives
during the day. We know the heat gain is 90 $\frac{joules}{second}$
and a day lasts 13.5 hours. We need to convert these 13.5 hours to seconds:

In [21]:
# 60 minutes in an hour and 60 seconds in a minute
seconds = 13.5 * 60 * 60
print("A day lasts", seconds, "seconds")

A day lasts 48600.0 seconds


Then we can calculate the total energy gain in joules:

In [22]:
# total energy gain is 90 joules per second times number of seconds
total_joules = 90 * seconds

We need to convert these joules to kcalories using the formula from earlier.

In [23]:
total_calories = total_joules/4.184
total_kcalories = total_calories/1000
print("Total kilocalories gained:", total_kcalories)

Total kilocalories gained: 1045.4110898661568


Now we can start answering our second question: how much water are we heating?
The only thing being heated is the water content of the camel.
Since 55% of the mass of the camel is water, we are heating 55% of 470 kg:

In [24]:
heatable_mass = (55/100) * 470
print("Total water mass being heated:", heatable_mass)

Total water mass being heated: 258.5


We can now start putting things together:
* we know the amount of kcal gained during the day

* we know the amount of water that is being warmed

* we know that 1kcal heats 1 kg (1000g) of water by 1 degree celsius

Note that the latter formula means that $x$ kcal gained by $y$ kg water
leads to a $\frac{x}{y}$ degrees celsius rise in temperature.
Make sure understand this...

In [25]:
total_temperature_rise = total_kcalories/heatable_mass
print("The camel becomes", total_temperature_rise, "degrees warmer during the day.")

The camel becomes 4.04414348110699 degrees warmer during the day.


With a starting temperature of 35.5 degrees celsius,
the final body temperature of the camel can now be calculated.
Let's round the temperature off here since we are at the end of our calculations:

In [26]:
end_of_day_temperature = round(35.5 + total_temperature_rise, 2)
print("The final body temperature of the camel is", end_of_day_temperature, "degrees celsius.")

The final body temperature of the camel is 39.54 degrees celsius.


All calculations gathered together into a single program:

In [27]:
seconds = 13.5 * 60 * 60
total_joules = 90 * seconds
total_calories = total_joules/4.184
total_kcalories = total_calories/1000
heatable_mass = (55/100) * 470
total_temperature_rise = total_kcalories/heatable_mass
end_of_day_temperature = round(35.5 + total_temperature_rise, 2)
print("The final body temperature of the camel is", end_of_day_temperature, "degrees celsius.")

The final body temperature of the camel is 39.54 degrees celsius.


<!-- --- end solution of exercise --- -->

**f)**
If the fat storage in the camel's hump would reduce the heat gain by 50%, what would then be the final body temperature at the end of the day?

<!-- --- begin answer of exercise --- -->
**Fasit.**
The final body temperature of the camel would then be 37.52 degrees celsius.
<!-- --- end answer of exercise --- -->

<!-- --- begin solution of exercise --- -->
**Løsningsforslag.**

In [28]:
# 50% of the heat gain is no longer going to the water
total_temperature_rise = 0.5 * total_kcalories/heatable_mass
end_of_day_temperature = round(35.5 + total_temperature_rise, 2)
print("The final body temperature of the camel is", end_of_day_temperature, "degrees celsius.")

The final body temperature of the camel is 37.52 degrees celsius.


<!-- --- end solution of exercise --- -->